account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfiletView.as_view(), name='user_profile'),

]

djangoTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('posts/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail')
]

account/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_posts')
    body = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    slug = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.slug} - {self.date_update}'

    def get_absolute_url(self):
        return reverse("home:post_detail", args=(self.id, self.slug))
    

account/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class UserRegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput({'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput({'class': 'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput({'class': 'form-control'}))
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput({'class': 'form-control'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('Your username is already use')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('Your email is already use')
        return email

    # this method is process on Register form with all fields not one fields (password)
    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')

        if p1 and p2 and p1 != p2:
            raise ValidationError('Your Pass not match!')


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput({'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput({'class': 'form-control'}))

account/views.py
from django.shortcuts import render, redirect
from django.views import View
from . import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from home.models import Post


# Create your views here.

class UserRegisterView(View):
    class_form = forms.UserRegisterForm
    template_name = 'account/register.html'

    def dispatch(self, request, *args, **kwargs):
        # disallow to execute get,post and another methods
        if request.user.is_authenticated:
            messages.error(request, 'you are past logged in', 'warning')
            return redirect('home:home')
        # allow to execute get,post and another methods
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.class_form()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.class_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password1'])
            messages.success(request, 'you have register', 'success')
            return redirect('home:home')

        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    class_form = forms.UserLoginForm
    template_name = 'account/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'you are past logged in', 'warning')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.class_form()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.class_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user:
                login(request, user)
                messages.info(request, 'you are logged in', 'info')
                return redirect('home:home')
            else:
                messages.error(request, 'username or password is not math', 'danger')

        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you are logged out', 'success')
        return redirect('home:home')


class UserProfiletView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(pk=user_id)
        # it's better to use the user instance to set a filter on access to user posts
        posts = Post.objects.filter(user=user)
        return render(request, 'account/profile.html', {'user': user, 'posts': posts})

home/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.models import User
from .models import Post


# Create your views here.

class HomeView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'home/index.html', {'posts': posts})


class PostDetailView(View):
    def get(self, request, post_id, post_slug):
        post = Post.objects.get(pk=post_id, slug=post_slug)
        return render(request, 'home/detail.html', {'post': post})


# def home(request):
#     return render(request, 'home/index.html')

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ post.user }}</h3>
    <h3>{{ post.user.id }}</h3>
    <p>{{ post.body }}</p>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <h3>Hello Django</h3>

    {% for post in posts %}
        <div class="card">
            <a href="{{post.get_absolute_url}}" class="card-body">{{ post.body }}</a>
        </div>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QA App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>

    {% include 'include/navbar.html' %}
    {% include 'include/messages.html' %}
    {% block content %}
    {% endblock %}
    {% include 'include/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/include/footer.html
<div class="bg-secondary p-2 text-white my-5">This is default footer</div>

templates/include/messages.html
<div class="col-md-6 p-2 m-4">
    {% if messages %}
        {% for msg in messages %}
            <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
        {% endfor %}
    {% endif %}
</div>

templates/include/navbar.html
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="#">QA APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-light" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
        {% if user.is_authenticated %}
            <a class="nav-link text-light" href="{% url 'account:user_logout' %}">Logout</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'account:user_profile' request.user.id %}">Profile</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'account:user_login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'account:user_register' %}">Register</a>
        </li>
        {% endif %}

{#        <li class="nav-item dropdown">#}
{#          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
{#            Dropdown#}
{#          </a>#}
{#          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#            <li><a class="dropdown-item" href="#">Action</a></li>#}
{#            <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#            <li><hr class="dropdown-divider"></li>#}
{#            <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#          </ul>#}
{#        </li>#}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>